### ISSUE TITLE
ceph s3 access from HUE gets timed out

### ISSUE THREAD

**Issue by bmv126** [cloudera/hue#1756]
Describe the bug:
I am trying to access S3 (ceph rgw) from Hue on K8s. The ceph is installed using rook. 

The ceph-rgw pod is exposed at port 8880. 
```
[root@vm-ceph]# kubectl get svc -n ceph | grep rgw
rook-ceph-rgw-rook-ceph-store             ClusterIP   10.254.110.19    <none>        8880/TCP            168d
```

I am using helm chart to bring up hue in K8s.   Below is the content of hue.ini in values.yaml file:
```
   [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id=W14156W0CWCJQZ
    secret_access_key=dBEE4ntWzW6z4nRjdM1ms1
    calling_format=boto.s3.connection.OrdinaryCallingFormat
    is_secure=false
    region=''
    host=rook-ceph-rgw-rook-ceph-store.ceph.svc.cluster.local
```

When trying to access the S3 filesystem from hue, it gets timed-out, as it is trying to access the ceph rgw at port 80 instead of 8880.

Steps to reproduce it?
Expose ceph rgw on non default insecure port (80).
Try to access ceph s3 store from hue. The connection request gets timed out. 
 

Hue version or source? 
Open source:  hue-4.9.0
Docker image used in values.yaml is  gethue/hue:20210208-135001

```
Observation:
Code is hardcoded to use port 80 for non secure cluster and 443 for secure cluster.
https://github.com/cloudera/hue/blob/44b40e51b1e9f2a11ce1be2f1f941cbeee3d97d6/desktop/core/ext-py/boto-2.46.1/boto/connection.py#L90
```

Can this be made configurable ?

**Comment by romainr** [comment]
`Can this be made configurable ?`

This comes from boto 2 itself, so either we are not using it properly (most probably, and would need to add a fix in Hue to call it properly + add a ini params https://github.com/cloudera/hue/blob/master/desktop/libs/aws/src/aws/conf.py#L160) or we need to modify boto 2 (that we ship in Hue currently).

**Comment by bmv126** [comment]
Thanks @romainr  for the reply.

I found a work around now on K8s by mapping the 8880 port to 80 port.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-rgw
    rook_object_store: rook-ceph-store
  name: rook-ceph-rgw-rook-ceph-store-internal
  namespace: ceph
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8880
  selector:
    app: rook-ceph-rgw
  type: ClusterIP
```
After creating a service, with above configuration it is working now.
