### ISSUE TITLE
Hue database dump not working on hue 4.8.0 

### ISSUE THREAD

**Issue by rahil-c** [cloudera/hue#2623]
#### Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? 

The issue is discussed in these forums
* https://discourse.gethue.com/t/when-hue-dumpdata-is-executed-tablehue-hive-query-doesnt-exist-is-displayed/531
* https://discourse.gethue.com/t/when-executing-hue-dumpdata-tablehue-hive-query-doesnt-exist-is-displayed/520

#### Describe the bug:

When running hue version 4.8.0 on AWS EMR 5.32.0, running the follow command 

`/usr/lib/hue/build/env/bin/hue dumpdata > ./hue-mysql.json`

it returns the following exception 
```
WARNINGS:
jobbrowser.DagDetails.dag_info: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
    HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
jobbrowser.QueryDetails.hive_query: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
    HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
CommandError: Unable to serialize database: (1146, "Table 'hue.hive_query' doesn't exist")
```
#### Cause of issue

*  It seems the main cause for the issue is that within the local mysql db on the cluster's master node, the `hive_query` table as well all other tables/models from the original [commit](https://github.com/cloudera/hue/commit/f999ac696c88c6c19060f37afaa7c019e28c8ba5) are not added within the local mysql database's alias for `hue`. 

#### Investigation

* In the comments of the [commit](https://github.com/cloudera/hue/commit/f999ac696c88c6c19060f37afaa7c019e28c8ba5) I suspect that some implementation has gone wrong from OSS hue, see comments from original contributor below

```
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
```
* the above `models.py` script can be manually modified on the cluster at this path `/usr/lib/hue/apps/jobbrowser/src/jobbrowser/models.py` however it seems that following the above suggestions such as Remove `managed = False` still does not create the `hive_query` or other tables.

## Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
open source hue 4.8.0+

#### Special Note
Can hue community please prioritize this fix, since it seems to be affecting several customers on AWS EMR.
