### ISSUE TITLE
No support for custom Docker images in Helm chart

### ISSUE THREAD

**Issue by kobethuwis** [cloudera/hue#2663]
**Describe the bug**

Hue 4.10.0 is deployed inside an AWS EKS Cluster, intended for querying data on AWS Athena. The Athena connector for Hue requires PyAthena to be installed, which is why an AWS ECR repository has been setup with a custom Docker image, based on gethue/hue:4.10.0.

The deployment-hue.yaml-template inside the helm chart for Hue however (1.0.3) forces the hue-init, hue & nginx containers to be installed from the official registry.

I suggest that the deployment-hue.yaml file should keep account of the image.repository value and allow for deployments from both the official and custom image repositories.

Hue version: 4.10.0
Helm chart version: 1.0.3
Kubernetes version 1.18

**deployment-hue.yaml**
```
[...]
{{ if eq .Values.hue.database.engine "postgresql_psycopg2" }}
      initContainers:
        - name: hue-init
          image: {{ .Values.image.registry }}/hue:{{ .Values.image.tag }} # TODO
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -s --connect-timeout 1 {{ .Values.hue.database.host }}:{{ .Values.hue.database.port }} || echo $?) -ne 52 ]; do
                sleep 1;
              done
{{ end }}
      containers:
      - name: hue
        image: {{ .Values.image.registry }}/hue:{{ .Values.image.tag }} # TODO
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8888
        resources:
          requests:
            # memory: "350Mi"
            cpu: "50m"
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/hue/desktop/conf/z-hue.ini
          subPath: hue-ini
        - name: config-volume-extra
          mountPath: /usr/share/hue/desktop/conf/zz-hue.ini
          subPath: hue-ini
        - name: hive-config-volume
          mountPath: /etc/hive/conf/hive-site.xml
          subPath: hive-site
        readinessProbe:
          httpGet:
            path: /desktop/debug/is_alive
            port: 8888
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 30
{{ if .Values.balancer.enabled }}
      - name: nginx
        image: {{ .Values.image.registry }}/nginx:{{ .Values.image.tag }} # TODO
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 80
        resources:
          requests:
            # memory: "64Mi"
            cpu: "20m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/sites-available/hue
          subPath: hue
{{ end }}
[...]
```
