### ISSUE TITLE
hostPath is hardcoded for Helm Charts

### ISSUE THREAD

**Issue by quovadisnp** [cloudera/hue#3638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In tools/kubernetes/helm/hue/templates/pv-postgres.yaml hostPath is hardcoded. The charts allow for overriding the storageClass but this provides no value if hostPath is hardcoded. hostPath should only be included if using host for storage. hostPath is also not valid for multi-node clusters making this unusable in real clusters. This blocks using any real storage class like EFS, longhorn, gp2, ...

```
{{- if and .Values.hue.database.persist .Values.hue.database.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.hue.database.storageName }}
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-pv
{{- end -}}
```

### Steps To Reproduce

Install charts and override postgres storage for values with any valid storageClass that isn't host-based
```
hue:
  database:
    storageName: "gp2"
```

### Logs

No relevant logs

### Hue version

Chart Version 1.0.3
