### ISSUE TITLE
Why session cookies are stored in the database ?

### ISSUE THREAD

**Issue by maaaaz** [cloudera/hue#465]
Hello hue team,

**User session cookies are stored** in the database, in the `django_session` table: `session_key` is the cookie and `session_data` holds the user id (in base64).
This is a **major security vulnerability** as someone having access to the database, for instance through [that other hue vulnerability](https://github.com/cloudera/hue/issues/446), can spoof a user across the entire cluster **launching jobs and browsing the datalake**, without having to crack its password hash.

The following example shows how an attacker could easily **find valid session cookies for a specific user (id=1).**
```
mysql> select * from django_session limit 1 \G ;
*************************** 1. row ***************************
 session_key: m67424cld61xe8960moyjj1esjqfiyvj
session_data: NGY2MzJhYjkxM2M5ZTU4ZDk0YjNjNjc4ODI1NmVkMzExMTI3YTc5NDp7Il9hdXRoX3VzZXJfYmFja2VuZCI6ImRlc2t0b3AuYXV0aC5iYWNrZW5kLkFsbG93Rmlyc3RVc2VyRGphbmdvQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOjF9
 expire_date: 2017-01-03 07:00:07
```
```
$ echo NGY2MzJhYjkxM2M5ZTU4ZDk0YjNjNjc4ODI1NmVkMzExMTI3YTc5NDp7Il9hdXRoX3VzZXJfYmFja2VuZCI6ImRlc2t0b3AuYXV0aC5iYWNrZW5kLkFsbG93Rmlyc3RVc2VyRGphbmdvQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOjF9 | base64 -d
4f632ab913c9e58d94b3c6788256ed311127a794:{"_auth_user_backend":"desktop.auth.backend.AllowFirstUserDjangoBackend","_auth_user_id":1}
```
```
mysql> select * from auth_user where id = 1 \G ;
*************************** 1. row ***************************
          id: 1
    password: pbkdf2_sha256$12000$dtbAVcdT4Ph9$4QMdEvX5Z0b5NFcPb69L50/cRo2ARFg/WCtk3/dcPw0=
  last_login: 2016-12-20 07:00:07
is_superuser: 1
    username: cloudera
  first_name: 
   last_name: 
       email: noreply@cloudera.com
    is_staff: 1
   is_active: 1
 date_joined: 2015-11-18 13:08:31
```

This vulnerability reminds me of Apache Ranger [doing the same](https://github.com/CERT-W/hadoop-attack-library/tree/master/Third-party%20modules%20vulnerabilities/Apache%20Ranger/CVE-2016-2174%20-%20Authenticated%20SQL%20injection#2-dump-and-reuse-user-session-jsessionid-cookies): really, that's a **bad practice** as it breaks the security boundary.

So if there's no real use of these cookies, they **shouldn't be logged in the database.**

On the same topic, you might know that authentication requests are also logged in the database in the `axes_accessattempt` table: all HTTP POST parameters are logged, except of course the [one named `password`](https://github.com/jazzband/django-axes/blob/ca55a6ef16acc2f8f5f0501de4ef8f0d2ccd6129/axes/decorators.py#L89). That is also playing with fire as the day the parameters is not named `password` anymore but something different, it will be logged.

Cheers.
